name: flutter_quill
description: A rich text editor built for the modern Android, iOS, web and desktop platforms. It is the WYSIWYG editor and a Quill component for Flutter.
version: 8.1.2
homepage: https://1o24bbs.com/c/bulletjournal/108
repository: https://github.com/singerdmx/flutter-quill
topics:
 - ui
 - widgets
 - widget
 - rich-text-editor
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^5.2.0
  quiver: ^3.1.0
  url_launcher: ^6.1.2
  pedantic: ^1.11.1
  characters: ^1.2.0
  diff_match_patch: ^0.4.1
  i18n_extension: ^6.0.0
  device_info_plus: ^4.0.0
  platform: ^3.1.0
  pasteboard: ^0.2.0
  equatable: ^2.0.5
  flutter_animate: ^4.2.0+1

  flutter_test:
    sdk: flutter
  meta: ^1.8.0

flutter: null